version: "3.7"

services:
  backend:
    build: ./server
    restart: always
    entrypoint: /app/backend/entrypoint.sh
    volumes:
      - ./server:/backend
    expose:
      - 5000

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx_witt
    restart: always
    ports:
      - "5001:80"
