version: "3.7"

services:
  backend:
    build: ./server
    restart: always
    entrypoint: /app/backend/entrypoint.sh
    volumes:
      - ./backend:/backend
    expose:
      - 8000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:80"
